version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./.env.prod
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 8585:8585
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod
